# -*- coding: utf-8 -*-
"""ClimateRisk.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K73fGAikmzf74LhMV3RtFy6ubViy42RQ
"""

!pip install -q xgboost shap scikit-learn pandas numpy matplotlib seaborn joblib

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_auc_score,
    average_precision_score
)

from xgboost import XGBClassifier

import joblib

from google.colab import drive

drive.mount('/content/drive')

!find /content/drive/MyDrive -name "Tamil_Nadu_Final_Hazard_Features.csv"

FILE = "/content/drive/MyDrive/ClimateData/Tamil_Nadu_Final_Hazard_Features.csv"

df = pd.read_csv(FILE)

print("Shape:", df.shape)
print(df.head())

print("Districts:", df["district"].nunique())

print(
    sorted(df["district"].unique())
)

print(
    "Date range:",
    df["date"].min(),
    "→",
    df["date"].max()
)

print("\nTargets:")
print("Flood:", df["flood"].sum())
print("Heatwave:", df["heatwave"].sum())
print("Drought:", df["drought"].sum())

df["date"] = pd.to_datetime(df["date"])

df = df.sort_values(
    ["date", "district"]
).reset_index(drop=True)

features = [
    "temp_max",
    "temp_min",
    "temp_mean",
    "temp_range",

    "humidity",
    "wind_speed",
    "pressure",
    "rainfall",
    "soil_wetness",

    "rainfall_3d",
    "rainfall_7d",
    "rainfall_30d",

    "temp_3d_mean",
    "temp_7d_mean",

    "temp_anomaly",
    "rainfall_anomaly",

    "SPI_3",
    "SPI_6",

    "month",
    "day_of_year"
]

df = pd.get_dummies(
    df,
    columns=["district"],
    dtype=int
)

train = df[
    df["date"] < "2022-01-01"
].copy()

validation = df[
    (df["date"] >= "2022-01-01") &
    (df["date"] < "2024-01-01")
].copy()

test = df[
    df["date"] >= "2024-01-01"
].copy()

print("Train:", train.shape)
print("Validation:", validation.shape)
print("Test:", test.shape)

target_columns = [
    "flood",
    "heatwave",
    "drought"
]

feature_columns = [
    col for col in df.columns
    if col not in [
        "date",
        "flood",
        "heatwave",
        "drought"
    ]
]

X_train = train[feature_columns]
X_val = validation[feature_columns]
X_test = test[feature_columns]

y_train = train[target_columns]
y_val = validation[target_columns]
y_test = test[target_columns]

print(
    X_train.isna().sum()
    [lambda x: x > 0]
)

import pandas as pd

FILE = "/content/drive/MyDrive/ClimateData/Tamil_Nadu_Final_Hazard_Features.csv"

df = pd.read_csv(FILE)

df["date"] = pd.to_datetime(df["date"])

print(df.columns.tolist())
print("District column exists:", "district" in df.columns)

missing_rain_anomaly = df[
    df["rainfall_anomaly"].isna()
][
    ["date", "district", "rainfall", "rainfall_anomaly"]
]

print(missing_rain_anomaly.head(20))
print("\nTotal missing:", len(missing_rain_anomaly))
print(
    missing_rain_anomaly["district"].value_counts()
)
missing_rain = df[
    df["rainfall_anomaly"].isna()
][
    ["date", "district", "rainfall", "rainfall_anomaly"]
]

print(missing_rain.head(20))
print("\nTotal missing:", len(missing_rain))

print("\nMissing by district:")
print(missing_rain["district"].value_counts())
print(
    df.loc[
        df["rainfall_anomaly"].isna(),
        "rainfall"
    ].isna().value_counts()
)

df["rainfall_anomaly"] = df["rainfall_anomaly"].fillna(0)

print(
    "Missing rainfall anomaly:",
    df["rainfall_anomaly"].isna().sum()
)

print(df.columns.tolist())

ml_features = [
    "temp_max",
    "temp_min",
    "temp_mean",
    "temp_range",
    "humidity",
    "wind_speed",
    "rainfall",
    "soil_wetness",
    "rainfall_3d",
    "rainfall_7d",
    "rainfall_30d",
    "temp_anomaly",
    "rainfall_anomaly",
    "SPI_3",
    "SPI_6"
]

# Keep only features that exist in your CSV
available_features = [
    col for col in ml_features
    if col in df.columns
]

missing_features = [
    col for col in ml_features
    if col not in df.columns
]

print("Available features:")
print(available_features)

print("\nMissing from dataset:")
print(missing_features)
print(
    df[available_features]
    .isna()
    .sum()
    .loc[lambda x: x > 0]
)

df["rainfall_anomaly"] = df["rainfall_anomaly"].fillna(0)

print("Missing rainfall anomaly:",
      df["rainfall_anomaly"].isna().sum())

ml_features = [
    "temp_max",
    "temp_min",
    "temp_mean",
    "temp_range",
    "humidity",
    "wind_speed",
    "rainfall",
    "soil_wetness",
    "rainfall_3d",
    "rainfall_7d",
    "rainfall_30d",
    "temp_anomaly",
    "rainfall_anomaly",
    "SPI_3",
    "SPI_6"
]

targets = [
    "flood",
    "heatwave",
    "drought"
]

df_ml = df.dropna(
    subset=ml_features
).copy()

print("Original dataset:", df.shape)
print("ML dataset:", df_ml.shape)
print("Rows removed:", len(df) - len(df_ml))

print(
    df_ml[ml_features].isna().sum()
)

# ============================================================
# 1. ML FEATURES AND TARGETS
# ============================================================

ml_features = [
    "temp_max",
    "temp_min",
    "temp_mean",
    "temp_range",
    "humidity",
    "wind_speed",
    "rainfall",
    "soil_wetness",
    "rainfall_3d",
    "rainfall_7d",
    "rainfall_30d",
    "temp_anomaly",
    "rainfall_anomaly",
    "SPI_3",
    "SPI_6"
]

targets = [
    "flood",
    "heatwave",
    "drought"
]

# Make sure date is datetime
df["date"] = pd.to_datetime(df["date"])

# Fix the 199 zero-variance rainfall anomaly cases
df["rainfall_anomaly"] = df["rainfall_anomaly"].fillna(0)

# Remove rows where required features are unavailable
df_ml = df.dropna(
    subset=ml_features + targets
).copy()

# Sort chronologically
df_ml = df_ml.sort_values(
    ["date", "district"]
).reset_index(drop=True)

print("Original dataset:", df.shape)
print("ML-ready dataset:", df_ml.shape)
print("Rows removed:", len(df) - len(df_ml))

print("\nMissing values in ML features:")

print(
    df_ml[ml_features]
    .isna()
    .sum()
)

print("\nMissing target values:")

print(
    df_ml[targets]
    .isna()
    .sum()
)

print("\nTarget distribution:")

for target in targets:

    print(f"\n{target.upper()}")

    print(
        df_ml[target]
        .value_counts()
    )

    print(
        "Positive rate:",
        round(
            df_ml[target].mean() * 100,
            3
        ),
        "%"
    )

# ============================================================
# 2. TIME-BASED SPLIT
# ============================================================

train = df_ml[
    df_ml["date"] < "2022-01-01"
].copy()

validation = df_ml[
    (df_ml["date"] >= "2022-01-01") &
    (df_ml["date"] < "2024-01-01")
].copy()

test = df_ml[
    df_ml["date"] >= "2024-01-01"
].copy()

print("TRAIN:")
print(train.shape)
print(train["date"].min(), "→", train["date"].max())

print("\nVALIDATION:")
print(validation.shape)
print(validation["date"].min(), "→", validation["date"].max())

print("\nTEST:")
print(test.shape)
print(test["date"].min(), "→", test["date"].max())

for name, data in [
    ("TRAIN", train),
    ("VALIDATION", validation),
    ("TEST", test)
]:

    print("\n==============================")
    print(name)
    print("==============================")

    for target in targets:

        positive = data[target].sum()
        total = len(data)

        print(
            f"{target:10s} "
            f"positive={positive:5d} "
            f"rate={positive/total*100:.3f}%"
        )

X_train = train[
    ml_features + ["district"]
].copy()

X_val = validation[
    ml_features + ["district"]
].copy()

X_test = test[
    ml_features + ["district"]
].copy()

y_train = train[
    targets
].copy()

y_val = validation[
    targets
].copy()

y_test = test[
    targets
].copy()

# ============================================================
# DISTRICT ONE-HOT ENCODING
# ============================================================

X_train = pd.get_dummies(
    X_train,
    columns=["district"],
    dtype=int
)

X_val = pd.get_dummies(
    X_val,
    columns=["district"],
    dtype=int
)

X_test = pd.get_dummies(
    X_test,
    columns=["district"],
    dtype=int
)

# Make validation/test columns exactly match training columns
X_val = X_val.reindex(
    columns=X_train.columns,
    fill_value=0
)

X_test = X_test.reindex(
    columns=X_train.columns,
    fill_value=0
)

print("X_train:", X_train.shape)
print("X_val:", X_val.shape)
print("X_test:", X_test.shape)

print("\nFinal feature columns:")
print(X_train.columns.tolist())

print("\nShapes:")

print("X_train:", X_train.shape)
print("y_train:", y_train.shape)

print("X_val:", X_val.shape)
print("y_val:", y_val.shape)

print("X_test:", X_test.shape)
print("y_test:", y_test.shape)

print(
    "X_train NaNs:",
    X_train.isna().sum().sum()
)

print(
    "X_val NaNs:",
    X_val.isna().sum().sum()
)

print(
    "X_test NaNs:",
    X_test.isna().sum().sum()
)

print(
    "y_train NaNs:",
    y_train.isna().sum().sum()
)

print(
    "y_val NaNs:",
    y_val.isna().sum().sum()
)

print(
    "y_test NaNs:",
    y_test.isna().sum().sum()
)

# ============================================================
# CLASS IMBALANCE WEIGHTS
# ============================================================

def calculate_scale_pos_weight(y):

    positive = y.sum()
    negative = len(y) - positive

    return negative / positive


flood_weight = calculate_scale_pos_weight(
    y_train["flood"]
)

heatwave_weight = calculate_scale_pos_weight(
    y_train["heatwave"]
)

drought_weight = calculate_scale_pos_weight(
    y_train["drought"]
)

print("Flood weight:", flood_weight)
print("Heatwave weight:", heatwave_weight)
print("Drought weight:", drought_weight)

train_processed = X_train.copy()

for target in targets:
    train_processed[target] = y_train[target].values

val_processed = X_val.copy()

for target in targets:
    val_processed[target] = y_val[target].values

test_processed = X_test.copy()

for target in targets:
    test_processed[target] = y_test[target].values

train_processed.to_csv(
    "/content/train_risk_dataset.csv",
    index=False
)

val_processed.to_csv(
    "/content/validation_risk_dataset.csv",
    index=False
)

test_processed.to_csv(
    "/content/test_risk_dataset.csv",
    index=False
)

print("Saved:")
print("train_risk_dataset.csv")
print("validation_risk_dataset.csv")
print("test_risk_dataset.csv")

from xgboost import XGBClassifier

def create_xgb(scale_pos_weight):
    return XGBClassifier(
        n_estimators=500,
        max_depth=6,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        objective="binary:logistic",
        eval_metric="aucpr",
        scale_pos_weight=scale_pos_weight,
        random_state=42,
        n_jobs=-1
    )

flood_model = create_xgb(flood_weight)

flood_model.fit(
    X_train,
    y_train["flood"],
    eval_set=[
        (X_val, y_val["flood"])
    ],
    verbose=False
)

print("Flood model trained.")

heatwave_model = create_xgb(heatwave_weight)

heatwave_model.fit(
    X_train,
    y_train["heatwave"],
    eval_set=[
        (X_val, y_val["heatwave"])
    ],
    verbose=False
)

print("Heatwave model trained.")

drought_model = create_xgb(drought_weight)

drought_model.fit(
    X_train,
    y_train["drought"],
    eval_set=[
        (X_val, y_val["drought"])
    ],
    verbose=False
)

print("Drought model trained.")

val_predictions = pd.DataFrame({
    "flood": flood_model.predict_proba(X_val)[:, 1],
    "heatwave": heatwave_model.predict_proba(X_val)[:, 1],
    "drought": drought_model.predict_proba(X_val)[:, 1]
})

val_predictions.head()

print("VALIDATION TARGET COUNTS")
print("========================")

for target in ["flood", "heatwave", "drought"]:
    print(
        target,
        "positive =",
        y_val[target].sum(),
        "total =",
        len(y_val),
        "rate =",
        round(y_val[target].mean() * 100, 4),
        "%"
    )

for target in ["flood", "heatwave", "drought"]:

    p = val_predictions[target]

    print("\n", target.upper())

    print("Minimum :", p.min())
    print("Maximum :", p.max())
    print("Mean    :", p.mean())
    print("Median  :", p.median())

    print(
        "Above 0.5:",
        (p >= 0.5).sum()
    )

    print(
        "Above 0.1:",
        (p >= 0.1).sum()
    )

for target in ["flood", "heatwave", "drought"]:

    events = y_val[target] == 1

    print("\n==============================")
    print(target.upper())
    print("==============================")

    print("Actual events:", events.sum())

    print("\nProbability for actual events:")
    print(
        val_predictions.loc[
            events, target
        ].describe()
    )

    print("\nProbability for non-events:")
    print(
        val_predictions.loc[
            ~events, target
        ].describe()
    )

# Reset indexes so X/y/predictions all align
X_val = X_val.reset_index(drop=True)
y_val = y_val.reset_index(drop=True)

X_test = X_test.reset_index(drop=True)
y_test = y_test.reset_index(drop=True)

val_predictions = pd.DataFrame({
    "flood": flood_model.predict_proba(X_val)[:, 1],
    "heatwave": heatwave_model.predict_proba(X_val)[:, 1],
    "drought": drought_model.predict_proba(X_val)[:, 1]
})

print(val_predictions.head())
print(val_predictions.shape)
print(y_val.shape)

for target in ["flood", "heatwave", "drought"]:

    events = y_val[target].to_numpy() == 1
    probabilities = val_predictions[target].to_numpy()

    print("\n==============================")
    print(target.upper())
    print("==============================")

    print("Actual events:", events.sum())

    print("\nProbability for ACTUAL events:")
    print(
        pd.Series(
            probabilities[events]
        ).describe()
    )

    print("\nProbability for NON-events:")
    print(
        pd.Series(
            probabilities[~events]
        ).describe()
    )

from sklearn.metrics import (
    roc_auc_score,
    average_precision_score
)

for target in ["flood", "heatwave", "drought"]:

    y_true = y_val[target].to_numpy()
    probability = val_predictions[target].to_numpy()

    print("\n==============================")
    print(target.upper())
    print("==============================")

    print(
        "ROC-AUC:",
        round(roc_auc_score(y_true, probability), 4)
    )

    print(
        "PR-AUC:",
        round(average_precision_score(y_true, probability), 4)
    )

print("TEST TARGET COUNTS")
print("==================")

for target in ["flood", "heatwave", "drought"]:
    print(
        target,
        "positive =",
        y_test[target].sum(),
        "total =",
        len(y_test),
        "rate =",
        round(y_test[target].mean() * 100, 4),
        "%"
    )

test_predictions = pd.DataFrame({
    "flood": flood_model.predict_proba(X_test)[:, 1],
    "heatwave": heatwave_model.predict_proba(X_test)[:, 1],
    "drought": drought_model.predict_proba(X_test)[:, 1]
})

print(test_predictions.head())
print("Shape:", test_predictions.shape)

from sklearn.metrics import (
    roc_auc_score,
    average_precision_score
)

for target in ["heatwave", "drought"]:

    y_true = y_test[target].to_numpy()
    probability = test_predictions[target].to_numpy()

    print("\n==============================")
    print(target.upper())
    print("==============================")

    print(
        "ROC-AUC:",
        round(
            roc_auc_score(
                y_true,
                probability
            ),
            4
        )
    )

    print(
        "PR-AUC:",
        round(
            average_precision_score(
                y_true,
                probability
            ),
            4
        )
    )

flood_by_year = (
    df_ml[df_ml["flood"] == 1]
    .assign(
        year=lambda x: x["date"].dt.year
    )
    .groupby("year")
    .size()
)

print(flood_by_year)

# ============================================================
# FLOOD-SPECIFIC TEMPORAL SPLIT
# ============================================================

flood_train = df_ml[
    df_ml["date"] < "2018-01-01"
].copy()

flood_val = df_ml[
    (df_ml["date"] >= "2018-01-01") &
    (df_ml["date"] < "2020-01-01")
].copy()

flood_test = df_ml[
    (df_ml["date"] >= "2020-01-01") &
    (df_ml["date"] < "2023-01-01")
].copy()

print("Flood TRAIN:")
print(flood_train.shape, "Flood events:", flood_train["flood"].sum())

print("\nFlood VALIDATION:")
print(flood_val.shape, "Flood events:", flood_val["flood"].sum())

print("\nFlood TEST:")
print(flood_test.shape, "Flood events:", flood_test["flood"].sum())

flood_features = [
    "temp_max",
    "temp_min",
    "temp_mean",
    "temp_range",
    "humidity",
    "wind_speed",
    "rainfall",
    "soil_wetness",
    "rainfall_3d",
    "rainfall_7d",
    "rainfall_30d",
    "temp_anomaly",
    "rainfall_anomaly",
    "SPI_3",
    "SPI_6"
]

X_flood_train = flood_train[
    flood_features + ["district"]
].copy()

X_flood_val = flood_val[
    flood_features + ["district"]
].copy()

X_flood_test = flood_test[
    flood_features + ["district"]
].copy()

y_flood_train = flood_train["flood"].copy()
y_flood_val = flood_val["flood"].copy()
y_flood_test = flood_test["flood"].copy()

X_flood_train = pd.get_dummies(
    X_flood_train,
    columns=["district"],
    dtype=int
)

X_flood_val = pd.get_dummies(
    X_flood_val,
    columns=["district"],
    dtype=int
)

X_flood_test = pd.get_dummies(
    X_flood_test,
    columns=["district"],
    dtype=int
)

# Make columns identical
X_flood_val = X_flood_val.reindex(
    columns=X_flood_train.columns,
    fill_value=0
)

X_flood_test = X_flood_test.reindex(
    columns=X_flood_train.columns,
    fill_value=0
)

print(X_flood_train.shape)
print(X_flood_val.shape)
print(X_flood_test.shape)

flood_pos = y_flood_train.sum()
flood_neg = len(y_flood_train) - flood_pos

flood_weight = flood_neg / flood_pos

print("Positive:", flood_pos)
print("Negative:", flood_neg)
print("scale_pos_weight:", flood_weight)

from xgboost import XGBClassifier

flood_model = XGBClassifier(
    n_estimators=500,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="binary:logistic",
    eval_metric="aucpr",
    scale_pos_weight=flood_weight,
    random_state=42,
    n_jobs=-1
)

flood_model.fit(
    X_flood_train,
    y_flood_train,
    eval_set=[
        (X_flood_val, y_flood_val)
    ],
    verbose=False
)

print("New Flood model trained.")

from sklearn.metrics import (
    classification_report,
    roc_auc_score,
    average_precision_score
)

flood_val_probability = flood_model.predict_proba(
    X_flood_val
)[:, 1]

print("Flood Validation ROC-AUC:",
      roc_auc_score(
          y_flood_val,
          flood_val_probability
      ))

print("Flood Validation PR-AUC:",
      average_precision_score(
          y_flood_val,
          flood_val_probability
      ))

flood_val_prediction = (
    flood_val_probability >= 0.5
).astype(int)

print(
    classification_report(
        y_flood_val,
        flood_val_prediction,
        digits=4,
        zero_division=0
    )
)

flood_test_probability = flood_model.predict_proba(
    X_flood_test
)[:, 1]

print("Flood Test ROC-AUC:",
      roc_auc_score(
          y_flood_test,
          flood_test_probability
      ))

print("Flood Test PR-AUC:",
      average_precision_score(
          y_flood_test,
          flood_test_probability
      ))
flood_test_prediction = (
    flood_test_probability >= 0.5
).astype(int)

print(
    classification_report(
        y_flood_test,
        flood_test_prediction,
        digits=4,
        zero_division=0
    )
)

# ============================================================
# FLOOD VALIDATION DIAGNOSTIC
# ============================================================

val_prob = flood_model.predict_proba(
    X_flood_val
)[:, 1]

val_events = y_flood_val.to_numpy() == 1

print("VALIDATION")
print("==============================")
print("Actual flood events:", val_events.sum())

print("\nProbability for ACTUAL floods:")
print(
    pd.Series(
        val_prob[val_events]
    ).describe()
)

print("\nProbability for NON-flood observations:")
print(
    pd.Series(
        val_prob[~val_events]
    ).describe()
)

# Compare the actual climate conditions
# between flood and non-flood observations

print("\nFlood-event feature means:")
print(
    flood_val.loc[
        flood_val["flood"] == 1,
        flood_features
    ].mean()
)

print("\nNon-flood feature means:")
print(
    flood_val.loc[
        flood_val["flood"] == 0,
        flood_features
    ].mean()
)

features = [
    "temp_max",
    "temp_min",
    "temp_mean",
    "temp_range",
    "humidity",
    "wind_speed",
    "rainfall",
    "soil_wetness",
    "rainfall_3d",
    "rainfall_7d",
    "rainfall_30d",
    "temp_anomaly",
    "rainfall_anomaly",
    "SPI_3",
    "SPI_6"
]

new_data = flood_test.iloc[[0]].copy()

X_new = new_data[
    flood_features + ["district"]
].copy()

X_new = pd.get_dummies(
    X_new,
    columns=["district"],
    dtype=int
)

X_new = X_new.reindex(
    columns=X_flood_train.columns,
    fill_value=0
)

flood_probability = flood_model.predict_proba(
    X_new
)[:, 1][0]

print("District:", new_data["district"].iloc[0])
print("Flood probability:", flood_probability)

new_data = test.iloc[[0]].copy()

X_new = new_data[
    ml_features + ["district"]
].copy()

X_new = pd.get_dummies(
    X_new,
    columns=["district"],
    dtype=int
)

X_new = X_new.reindex(
    columns=X_train.columns,
    fill_value=0
)

flood_probability = flood_model.predict_proba(
    X_new
)[:, 1][0]

heatwave_probability = heatwave_model.predict_proba(
    X_new
)[:, 1][0]

drought_probability = drought_model.predict_proba(
    X_new
)[:, 1][0]

print("District:", new_data["district"].iloc[0])

print("Flood:", flood_probability)
print("Heatwave:", heatwave_probability)
print("Drought:", drought_probability)

def risk_level(p):
    if p >= 0.70:
        return "HIGH"
    elif p >= 0.40:
        return "MEDIUM"
    else:
        return "LOW"
print("Flood:",
      risk_level(flood_probability))

print("Heatwave:",
      risk_level(heatwave_probability))

print("Drought:",
      risk_level(drought_probability))

